### ISSUE TITLE
Просьба проверить домашнее задание

### ISSUE THREAD

**Issue by dbvech** [dbvech/typing-practice#1]
@JSMonk

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
1. У Вас нет никакой валидации для эмейла и пароля (мы ведь можем прокинуть вообще пустые строки).
2. Давайте попробуем добавить более конкретные типы [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...dbvech:homework#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR7) (Мы не зря оставили [этот комментарий](https://github.com/JSMonk/typing-practice/compare/homework-task...dbvech:homework#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR7)).
3. Давайте попробуем описать [эту бизнесс логику](https://github.com/JSMonk/typing-practice/compare/homework-task...dbvech:homework#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R49) на типах, как мы делали для ролей и операций на лекциях.

**Comment by dbvech** [comment]
Здравствуйте, Артем. Так все пункты ТЗ выполнены :)
А если серьезно:
2. Не совсем понял, добавить более конкретные типы на вход функции? Тогда надо добавить какой-то метод в логин сервис типо validate который будет принимать строки а отдавать тип Email и Password или ошибку, а на аргументы логина поставить типы Email и Password. И в use-login сначала вызывать validate а потом уже login. Я правильно понял? Или вызывать validate внутри login, но тогда входные аргументы останутся типом string. 
3. Логика которую я написал с точки зрения рантайма рабочая? Не совсем понимаю для чего ее писать еще и на типах. Можете пожалуйста объяснить уязвимые места моей реализации. Я так понимаю мы пишем сервисы как что-то надежное (предполагаем что там все правильно) и пишем все эти типы для того чтобы другие программисты пользуясь нашим сервисом не могли передать туда что-то не то. Типы помогают выявить эти ошибки на этапе компиляции, а проверки по instanceof Class будут кидать эксепшоны в рантайме защищая БЛ. Не до конца понял тему

Спасибо

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
1. Да, на вход функции. Но, можно отдельный метод не делать, а сделать у `Email` и `Password` статические методы , который будет вызывать конструкто (или просто вызывать конструктор), ведь он и так будет возвращать экземпляр этого типа.
```javascript
loginService.login(Email.from(credentials.email), Password.from(credentials.password))
  .then(...);
```
2. Проблема Вашей реализации в том, что у нас нет быстрого способа определить, правильная ли бизнес-логика. Для того, что бы Вы поймали эти исключения в рантайме - нам нужно будет посетить страницу и наклацать (руками или E2E-тестами) такую ситуацию, что бы исключение было брошено. Когда Вы комбинируете рантайм ошибки и ошибки компиляции - Вы находите такие ошибки в реализации на моменте компиляции + если инструмент не такой безопасный, Вы подстраховываетесь исключениями в рантайме. Так что ответ на вопрос "для чего" - что бы быстрее находить ошибки и, как результат, получать более надежное и безопасное решение.

**Comment by dbvech** [comment]
@JSMonk, Здравствуйте. Помогите пожалуйста с [этим](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkAaGAYQBkyBRCgFRgF8BYAKFElgIUMAPIAHOACcAhlACW4PLxgwAqgAUiBVkwD6rEbuLlqytZu16Duhsza9uPXsEzSIEQgBNkcsEp4qYpJyAG6yOJJw0p7gmACeMLpQcRIwALwwAMpxyABGWAAUAEQE3r5FAJQA3GaR0bEJklg4GRjYAHTGlDU8js6u7nSYcgiwuGZBoeEwdTFg8YnJqRnZeYVFtMOjlT0qsw0zzenoze22LKw9fTxLOKoQUselPn4APkMjYFA9zuDQMOomGhyJlMmQRBRMroAEIATV0aBE9CYx3GARgAG02nAzowLgBdABc-hUKk8bgAFvlpJJPMSAGbSTAPKhmFQgCQyeR-Ym4Dis9H8sxY05dChEkmk8kQKkgGl0mBQSSIOAC0kwDlSWQKSC8tmkkUdMUSjHiLXcsDtDRaHT6QznNj4tXqzHY3F2Vgms1cnVWiy26zG-WOFSODgwNwwfjQH43FI4QHAsig8GQmHwxHI463ED0gFAkFgiFQuEIpFMWPR2AAczgUHuUnUUh87h1HgyAB40PAAB5QBCeDzYgB8BUQD0kxIbkhgADI8IdsMTuxwKulh5LIlBEJI-InC6mSxnyxjx1J2k1sPirrxfgII2U-BkwHAAO5eF4Fap3-4uT6wZ83w+UYv1vHhPDgFwaRwMIZzPSc1AnHoIKgyIYFgqMd0iL5pynJCwLkPMxwnGBfGgaQwGAOBc2Ar41zRFQqxgTkWwgNtjlresJybSRWLbYipGqGAAHphJgQBxEEADhBACEQQAGEEAORBpMAQRBAHkQGBAH4QQABEFkwAmEEkwBuEEAGRBAF4QQA+EAcAiiPg0iBAoqiaOeXx6LMJiWLkVs-g4utpx4vi-gEyQhNEiSZIU5S1K03SDJM8zejApjOIIMI5FcXJsG9bVPM7NAAEZe37MBBxObAaDQAAmfKByHZpR3gvDHnnfBLzgZc8v5TDJGwripHqmdGsXFr0Aq1d10lVzm3ctispgTifImjzIC7MrR2ALDRmnIKxMivSjLMmB9MkiTpNMmA1OkwBhEGkjTAFYQTTrsAFhBZP0mB7sANhBruM27JMALhAhoAfhga6lIOwHAGYQE7zsARhBtOkwyYEh877uuq7TMACRBJMh77ZNqOsdz8NyFogU8JwvZp8XaTUfT+Ynz2a68RLErHfskpTtpkuGLpR9HMfOv6LKcPg-lgSnMsgLyoCS6QUukNK4Ayi0IACmhVs69aJ02o7TMhmAlPkx6YB00zAHYQHTtMASRAntUmBpMk9TLJgAKbPIyjqLzTZ-znecVa66cnagOzXY-JyxqFjVOVF9sZrrSXpdl+X+Pg5W1pw9WqgZmBDvE47td1-XDZN82npZjnTPE4zAGkQa6YFM9TbtkwAxEEkw6HCAA) примером

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
Вот немного измененный и рабочий [пример](DkAaGAYQBkyBRCgFRgF8BYAKFElgIUMAPIAHOACcAhlACW4PLxgwAqgAUiBVkwD6rEbuLlqytZu16Duhsza9uPXsEzSIEQgBNkcsEp4qYpJyAG6yOJJw0p7gmACeMLpQcRIwALwwAMpxyABGWAAUAEQE3r5FAJQA3GaR0bEJklg4GRjYAHTGlDU8js6u7nSYcgiwuGZBoeEwdTFg8YnJqRnZeYVFtMOjlT0qsw0zzenoze22LKw9fTxLOKoQUselPn4APkMjYFA9zuDQMOomGhyJlMmQRBRMroAEIATV0aBE9CYx3GARgAG02nAzowLgBdABc-hUKk8bgAFvlpJJPMSAGbSTAPKhmFQgCQyeR-Ylo0mkgD0ApggFwQQDCIIA2EEAvCCAPhAYIB+EEAAiAywCCIIAhEDlgBYQGWARhBAAwggCYQQAcIGrADIgMGVgG4QQCsIIBOEBgKsAciCavUwNmk90qLGnLoUImY-Gs9H870dc5sf0Y-G8GPBzhBlQcBOY7GdUiUf180nkiBUkA0ukwKCSRBwZPszmyBSQXmelM+9N+4kY8RSKvgdoaLQ6fSGcOsQN10M4-uR1tc6udiw96y+6NxxyJhwwNwwfjQH43FI4QHAsig8GQmHwxHI463ED0gFAkFgiFQuEIpFMTdCmCAFBBdYaTebAPIgBqlQBpEHtNUjXlX4BBgABzOAoHuKR1CkHx3GrDwMgAHjQeAAA8oAQTwPGxAA+ApEAeSRiXgyQYAAMjwQ5sGJLCOAqYld1vQ8HxPZ8sXxdIiJJGZYMQSQ-HY-c7yPR9TyYDEyKkdommwfErljddYGiF5jjAOAAHcvBeApqgg-4XE+WAMh0-TNnMozY08OAXBpHAwmo+SKLUciegcpzIhgVy1xEyIvioyivNjOQr1I8iYF8aBpDAYA4EvD5RgqQT1JgTlkIgVDjhguDyMQyQctQ6KpGqGA30AcRATT1R01RVX8FUVb9LVNWUHAiqL3NigQEqSlLnl8dKs0y7K5BQv58tgqjitKv5yskSqarqhqmpatqOplLqnD4P5YAKggwjkVxcmwcd20gY50LMNAAEYcLwsACJObAaDugAmJ78MI5peBIsx3LCx46PwJS4CYx6kzMYAgtGULPNB+iIaY77HFY689wPe9jyfZEsU+-EMSKDk225SAimJh6+LSASxoOrKkMm3LpoyAq5uZqbIEwz6SLhyRgsKiqqiq4UlS22UYEtI0YGqjUYGatUxTVBVrUVa0XUtGBNQla0pXVo1AC4QdBPoAfhga0VRly3AGYQOUxR1VqzRgHUxU1a1VZlQAJECNHUjb1WphNEpmSpZ1D2jJic-jk8jFOaFSxZgAOTaNFUJeNF3la933-bFM3dpM2Ao6utDoNg47pFO6RzrgS6KYgJaaAFoWqJW4V5d1B1nVdA0ZUAdhADVawBJED1S0NtA8C9simAlr6+LEuSq8bNGWi6JbhGYriqABqXgyRoyxmS4bmaoEr6va-rsr3Ob+GQvI9uYFlzudW7l0YD7weR7HtPzQ1aqgLWhgDKeU6s9SADEQI0ssHBAA)

**Comment by dbvech** [comment]
@JSMonk ссылка битая

**Comment by JSMonk** [comment]
Прошу прощения, что так долго отвечал.
Вот [исправленная ссылка](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkAaGAYQBkyBRCgFRgF8BYAKFElgIUMAPIAHOACcAhlACW4PLxgwAqgAUiBVkwD6rEbuLlqytZu16Duhsza9uPXsEzSIEQgBNkcsEp4qYpJyAG6yOJJw0p7gmACeMLpQcRIwALwwAMpxyABGWAAUAEQE3r5FAJQA3GaR0bEJklg4GRjYAHTGlDU8js6u7nSYcgiwuGZBoeEwdTFg8YnJqRnZeYVFtMOjlT0qsw0zzenoze22LKw9fTxLOKoQUselPn4APkMjYFA9zuDQMOomGhyJlMmQRBRMroAEIATV0aBE9CYx3GARgAG02nAzowLgBdABc-hUKk8bgAFvlpJJPMSAGbSTAPKhmFQgCQyeR-Ylo0mkrGnLoUImY-Gs9H8wUdc5sUUY-FszgSlQcFWY7GdUiUUV80nkiBUkA0ukwKCSRBwdXszmyBSQXlKlTSnHC+XiKR28DtDRaHT6Qyy1jip0a05B9227lgH0Wf3WN1KxyqhwwNwwfjQH43FI4QHAsig8GQmHwxHI463ED0gFAkFgiFQuEIpFMbOZ2AAczgUHuUnUUh87ntHgyAB40PAAB5QBCeDzYgB8BUQD0kxL7khgADI8IdsMTJxwKsT8-Xi02y62sfj0ouSTMe4hJH4z4WGyXm+WmBjV1J2k02D4lcvC-AIaZlH4GRgHAADuXgvAU1Rgf8LifLA0FwR8oxIaBPCeHALg0jgYRbn+65qGuPQEURkQwKRGbPpEXybhuVF4XINYrmuMC+NA0hgMAcDVthXwVA+HYwJyQ4QCOxzdr2a4DpIMkjtxUjVDAAD0WkwIA4iCABwggBCIIADCCAHIgRmAIIggDyIDAgD8IIAAiAmYATCAGYA3CCADIggC8IIAfCAOBxXHkbxAgCUJInPL44l6pJ0lyMOfzyT2m7KapfzqZImk6fpxnmVZtmOS57neX5vR4ZJCkEGEciuLk2AelycnjmgACM06zmA84nNgNBoAATG1c4Ls0y7kWxjy7vggFwIerVqoxkjMYpUhjVuE37tN6D9cep51u+F6li2yJYr1+IYkUHKetGEBFKdLW3mk97RX8sCxfFkCJUtkgpXFsl-BOvXLsATGjJumW6QVrmeb5MBuQZ+lGT5MC2UZgDCIEZ9mAKwgDkY4ALCAmW5MA44AbCAY15WMGYAXCCbQA-DAGOWbDdOAMwgiMo4AjCBOUZHkwGzKM4xj6M+YAEiAGWzFMmbUT4vlJg4-SO7QXQ1fy-muAHNMB2m6eLVMGZZEPGdzqOCyLYso9T-lOHwz0wIrXrvRkFVVTVdVRmp5E0EDC0g2uYPwz5bMwJZZl4zAzk+YA7CDOU5gCSIPjNkwEZBl2QFMDpcF-GCcJNabOhO67p7i2bunUChVnCGRRJ1u21dH2VdI1XSLVcD1XbEDpR7wMsT7VSazAcN6QjAdByHYeRzH+O64bPl6V5gDSIBjMA+XZWMmYAYiAGXDDhAA).

**Comment by dbvech** [comment]
@JSMonk спасибо. Проверьте плз ДЗ

**Comment by dbvech** [comment]
@JSMonk добрый день. Пинганул еще раз, вдруг Вы пропустили предыдущее сообщение

**Comment by JSMonk** [comment]
Красиво. Давайте только [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...dbvech:homework#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R57) возвращаемый тип укажем, потому что этот красиво-выведенный тип через функцию не будет работать (проблема TypeScript).

**Comment by dbvech** [comment]
fixed

**Comment by JSMonk** [comment]
Кул. Задание принято. Хорошая работа 👍

**Comment by dbvech** [comment]
Спасибо
