### ISSUE TITLE
Просьба проверить домашнее задание (контракты)

### ISSUE THREAD

**Issue by dbvech** [dbvech/typing-practice#2]
@JSMonk, здравствуйте. Проверьте пожалуйста дз по контрактам

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
Всее хорошо - задача принята. 
Хорошая работа (очень нравится решение с permissions на страницыы внутри объекта) 👍🏻 
P.S. [Здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...dbvech:homework-contracts#diff-b712f225ef9aab3eb0897f3f20d97ba6c9db26525745bd68d7fac359dc9e70cfR3) и [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...dbvech:homework-contracts#diff-40dcdaf58e0d1fa64d3c9f0b0adbb87e24d2a266d549ae7c066974d7931784dfR8) маленькое уточнение. У Вас в функцию точно-точно придет строка (иначе `runtypes` кинет исключение), так что можно спокойно ставить в аргументе тип `string` и убрать проверку на строку (Вы просто повторяете такую же проверку, что и внутри `runtypes`.

**Comment by dbvech** [comment]
Здравствуйте, Артем. 
Спасибо за ревью. Рад получить от Вас позитивный фидбек 😊
P.S. По поводу проверок на строку - забыл убрать... 😞 . Поправил и залил без них.
